#create_clock -period 10.000 -name CLK_100M_0 [get_ports FPGA_DDR4_100M_CLK0P]
#create_clock -period 10.000 -name CLK_100M-1 [get_ports FPGA_DDR4_100M_CLK1P]

set_property PACKAGE_PIN H31 [get_ports FPGA_DDR4_100M_CLK0P]
set_property PACKAGE_PIN G31 [get_ports FPGA_DDR4_100M_CLK0N]
set_property PACKAGE_PIN J20 [get_ports FPGA_DDR4_100M_CLK1P]
set_property PACKAGE_PIN J19 [get_ports FPGA_DDR4_100M_CLK1N]


set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_pins -hier -filter {NAME =~ */u_ddr4_infrastructure/gen_mmcme3.u_mmcme_adv_inst/CLKIN1}]


#BANK48

#BANK46


#BANK47
#set_property PACKAGE_PIN  A29  [get_ports {#DDR4_IF0\.ddr4_par}]
#set_property PACKAGE_PIN  E30  [get_ports {#DDR4_IF0\.ddr4_alert#}]

#BANK66

#BANK67
#set_property PACKAGE_PIN  B17  [get_ports {#DDR4_IF1\.ddr4_par}]
#set_property PACKAGE_PIN  F17  [get_ports {#DDR4_IF1\.ddr4_alert#}]

#BANK68

set_property PACKAGE_PIN C14 [get_ports {DDR4_IF1\.ddr4_dq[63]}]
set_property PACKAGE_PIN B14 [get_ports {DDR4_IF1\.ddr4_dq[57]}]
set_property PACKAGE_PIN B16 [get_ports {DDR4_IF1\.ddr4_dq[56]}]
set_property PACKAGE_PIN B15 [get_ports {DDR4_IF1\.ddr4_dq[58]}]
set_property PACKAGE_PIN C12 [get_ports {DDR4_IF1\.ddr4_dqs_t[7]}]
set_property PACKAGE_PIN B12 [get_ports {DDR4_IF1\.ddr4_dqs_c[7]}]
set_property PACKAGE_PIN A15 [get_ports {DDR4_IF1\.ddr4_dq[60]}]
set_property PACKAGE_PIN A14 [get_ports {DDR4_IF1\.ddr4_dq[62]}]
set_property PACKAGE_PIN D13 [get_ports {DDR4_IF1\.ddr4_dq[61]}]
set_property PACKAGE_PIN C13 [get_ports {DDR4_IF1\.ddr4_dq[59]}]
set_property PACKAGE_PIN A13 [get_ports {DDR4_IF1\.ddr4_dm_dbi_n[7]}]
set_property PACKAGE_PIN E13 [get_ports {DDR4_IF1\.ddr4_dq[51]}]
set_property PACKAGE_PIN E12 [get_ports {DDR4_IF1\.ddr4_dq[55]}]
set_property PACKAGE_PIN E16 [get_ports {DDR4_IF1\.ddr4_dq[50]}]
set_property PACKAGE_PIN D16 [get_ports {DDR4_IF1\.ddr4_dq[52]}]
set_property PACKAGE_PIN F13 [get_ports {DDR4_IF1\.ddr4_dqs_t[6]}]
set_property PACKAGE_PIN F12 [get_ports {DDR4_IF1\.ddr4_dqs_c[6]}]
set_property PACKAGE_PIN D15 [get_ports {DDR4_IF1\.ddr4_dq[48]}]
set_property PACKAGE_PIN D14 [get_ports {DDR4_IF1\.ddr4_dq[49]}]
set_property PACKAGE_PIN G14 [get_ports {DDR4_IF1\.ddr4_dq[54]}]
set_property PACKAGE_PIN F14 [get_ports {DDR4_IF1\.ddr4_dq[53]}]
set_property PACKAGE_PIN F15 [get_ports {DDR4_IF1\.ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN J14 [get_ports {DDR4_IF1\.ddr4_dq[42]}]
set_property PACKAGE_PIN H14 [get_ports {DDR4_IF1\.ddr4_dq[40]}]
set_property PACKAGE_PIN G16 [get_ports {DDR4_IF1\.ddr4_dq[44]}]
set_property PACKAGE_PIN G15 [get_ports {DDR4_IF1\.ddr4_dq[46]}]
set_property PACKAGE_PIN K13 [get_ports {DDR4_IF1\.ddr4_dqs_t[5]}]
set_property PACKAGE_PIN K12 [get_ports {DDR4_IF1\.ddr4_dqs_c[5]}]
set_property PACKAGE_PIN K15 [get_ports {DDR4_IF1\.ddr4_dq[43]}]
set_property PACKAGE_PIN J15 [get_ports {DDR4_IF1\.ddr4_dq[41]}]
set_property PACKAGE_PIN L13 [get_ports {DDR4_IF1\.ddr4_dq[47]}]
set_property PACKAGE_PIN L12 [get_ports {DDR4_IF1\.ddr4_dq[45]}]
set_property PACKAGE_PIN J13 [get_ports {DDR4_IF1\.ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN P15 [get_ports {DDR4_IF1\.ddr4_dq[39]}]
set_property PACKAGE_PIN P14 [get_ports {DDR4_IF1\.ddr4_dq[35]}]
set_property PACKAGE_PIN M15 [get_ports {DDR4_IF1\.ddr4_dq[34]}]
set_property PACKAGE_PIN L15 [get_ports {DDR4_IF1\.ddr4_dq[38]}]
set_property PACKAGE_PIN N12 [get_ports {DDR4_IF1\.ddr4_dqs_t[4]}]
set_property PACKAGE_PIN M12 [get_ports {DDR4_IF1\.ddr4_dqs_c[4]}]
set_property PACKAGE_PIN N14 [get_ports {DDR4_IF1\.ddr4_dq[32]}]
set_property PACKAGE_PIN M14 [get_ports {DDR4_IF1\.ddr4_dq[36]}]
set_property PACKAGE_PIN R13 [get_ports {DDR4_IF1\.ddr4_dq[37]}]
set_property PACKAGE_PIN R12 [get_ports {DDR4_IF1\.ddr4_dq[33]}]
set_property PACKAGE_PIN P13 [get_ports {DDR4_IF1\.ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN A18 [get_ports {DDR4_IF1\.ddr4_reset_n}]
set_property PACKAGE_PIN A17 [get_ports {DDR4_IF1\.ddr4_adr[8]}]
set_property PACKAGE_PIN D20 [get_ports {DDR4_IF1\.ddr4_adr[10]}]
set_property PACKAGE_PIN B20 [get_ports {DDR4_IF1\.ddr4_adr[5]}]
set_property PACKAGE_PIN A20 [get_ports {DDR4_IF1\.ddr4_act_n}]
set_property PACKAGE_PIN C17 [get_ports {DDR4_IF1\.ddr4_adr[11]}]
set_property PACKAGE_PIN B19 [get_ports {DDR4_IF1\.ddr4_adr[1]}]
set_property PACKAGE_PIN A19 [get_ports {DDR4_IF1\.ddr4_adr[9]}]
set_property PACKAGE_PIN D18 [get_ports {DDR4_IF1\.ddr4_adr[12]}]
set_property PACKAGE_PIN C18 [get_ports {DDR4_IF1\.ddr4_adr[3]}]
set_property PACKAGE_PIN D19 [get_ports {DDR4_IF1\.ddr4_adr[15]}]
set_property PACKAGE_PIN C19 [get_ports {DDR4_IF1\.ddr4_ba[1]}]
set_property PACKAGE_PIN F18 [get_ports {DDR4_IF1\.ddr4_adr[2]}]
set_property PACKAGE_PIN E18 [get_ports {DDR4_IF1\.ddr4_adr[6]}]
set_property PACKAGE_PIN F20 [get_ports {DDR4_IF1\.ddr4_adr[14]}]
set_property PACKAGE_PIN E20 [get_ports {DDR4_IF1\.ddr4_cke[0]}]
set_property PACKAGE_PIN E17 [get_ports {DDR4_IF1\.ddr4_cs_n[0]}]
set_property PACKAGE_PIN G20 [get_ports {DDR4_IF1\.ddr4_odt[0]}]
set_property PACKAGE_PIN F19 [get_ports {DDR4_IF1\.ddr4_ba[0]}]
set_property PACKAGE_PIN H18 [get_ports {DDR4_IF1\.ddr4_adr[0]}]
set_property PACKAGE_PIN H17 [get_ports {DDR4_IF1\.ddr4_adr[13]}]
set_property PACKAGE_PIN G17 [get_ports {DDR4_IF1\.ddr4_adr[7]}]
set_property PACKAGE_PIN H19 [get_ports {DDR4_IF1\.ddr4_bg[0]}]
set_property PACKAGE_PIN G19 [get_ports {DDR4_IF1\.ddr4_adr[4]}]
set_property PACKAGE_PIN K18 [get_ports {DDR4_IF1\.ddr4_adr[16]}]
set_property PACKAGE_PIN L19 [get_ports {DDR4_IF1\.ddr4_ck_t[0]}]
set_property PACKAGE_PIN L18 [get_ports {DDR4_IF1\.ddr4_ck_c[0]}]
set_property PACKAGE_PIN D21 [get_ports {DDR4_IF1\.ddr4_dq[31]}]
set_property PACKAGE_PIN C21 [get_ports {DDR4_IF1\.ddr4_dq[29]}]
set_property PACKAGE_PIN B21 [get_ports {DDR4_IF1\.ddr4_dq[25]}]
set_property PACKAGE_PIN A22 [get_ports {DDR4_IF1\.ddr4_dq[27]}]
set_property PACKAGE_PIN C22 [get_ports {DDR4_IF1\.ddr4_dqs_t[3]}]
set_property PACKAGE_PIN B22 [get_ports {DDR4_IF1\.ddr4_dqs_c[3]}]
set_property PACKAGE_PIN B24 [get_ports {DDR4_IF1\.ddr4_dq[30]}]
set_property PACKAGE_PIN A24 [get_ports {DDR4_IF1\.ddr4_dq[26]}]
set_property PACKAGE_PIN D23 [get_ports {DDR4_IF1\.ddr4_dq[24]}]
set_property PACKAGE_PIN C23 [get_ports {DDR4_IF1\.ddr4_dq[28]}]
set_property PACKAGE_PIN D24 [get_ports {DDR4_IF1\.ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN F23 [get_ports {DDR4_IF1\.ddr4_dq[22]}]
set_property PACKAGE_PIN E23 [get_ports {DDR4_IF1\.ddr4_dq[18]}]
set_property PACKAGE_PIN E21 [get_ports {DDR4_IF1\.ddr4_dq[19]}]
set_property PACKAGE_PIN E22 [get_ports {DDR4_IF1\.ddr4_dq[23]}]
set_property PACKAGE_PIN G24 [get_ports {DDR4_IF1\.ddr4_dqs_t[2]}]
set_property PACKAGE_PIN F24 [get_ports {DDR4_IF1\.ddr4_dqs_c[2]}]
set_property PACKAGE_PIN G21 [get_ports {DDR4_IF1\.ddr4_dq[17]}]
set_property PACKAGE_PIN G22 [get_ports {DDR4_IF1\.ddr4_dq[21]}]
set_property PACKAGE_PIN H23 [get_ports {DDR4_IF1\.ddr4_dq[16]}]
set_property PACKAGE_PIN H24 [get_ports {DDR4_IF1\.ddr4_dq[20]}]
set_property PACKAGE_PIN H21 [get_ports {DDR4_IF1\.ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN J23 [get_ports {DDR4_IF1\.ddr4_dq[11]}]
set_property PACKAGE_PIN J24 [get_ports {DDR4_IF1\.ddr4_dq[9]}]
set_property PACKAGE_PIN K22 [get_ports {DDR4_IF1\.ddr4_dq[10]}]
set_property PACKAGE_PIN K23 [get_ports {DDR4_IF1\.ddr4_dq[14]}]
set_property PACKAGE_PIN M20 [get_ports {DDR4_IF1\.ddr4_dqs_t[1]}]
set_property PACKAGE_PIN M21 [get_ports {DDR4_IF1\.ddr4_dqs_c[1]}]
set_property PACKAGE_PIN L20 [get_ports {DDR4_IF1\.ddr4_dq[15]}]
set_property PACKAGE_PIN K20 [get_ports {DDR4_IF1\.ddr4_dq[13]}]
set_property PACKAGE_PIN L23 [get_ports {DDR4_IF1\.ddr4_dq[8]}]
set_property PACKAGE_PIN L24 [get_ports {DDR4_IF1\.ddr4_dq[12]}]
set_property PACKAGE_PIN K21 [get_ports {DDR4_IF1\.ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN R20 [get_ports {DDR4_IF1\.ddr4_dq[7]}]
set_property PACKAGE_PIN P20 [get_ports {DDR4_IF1\.ddr4_dq[3]}]
set_property PACKAGE_PIN R21 [get_ports {DDR4_IF1\.ddr4_dq[1]}]
set_property PACKAGE_PIN P21 [get_ports {DDR4_IF1\.ddr4_dq[4]}]
set_property PACKAGE_PIN N21 [get_ports {DDR4_IF1\.ddr4_dqs_t[0]}]
set_property PACKAGE_PIN N22 [get_ports {DDR4_IF1\.ddr4_dqs_c[0]}]
set_property PACKAGE_PIN T22 [get_ports {DDR4_IF1\.ddr4_dq[5]}]
set_property PACKAGE_PIN R22 [get_ports {DDR4_IF1\.ddr4_dq[6]}]
set_property PACKAGE_PIN P23 [get_ports {DDR4_IF1\.ddr4_dq[0]}]
set_property PACKAGE_PIN N23 [get_ports {DDR4_IF1\.ddr4_dq[2]}]
set_property PACKAGE_PIN T23 [get_ports {DDR4_IF1\.ddr4_dm_dbi_n[0]}]

set_property PACKAGE_PIN B25 [get_ports {DDR4_IF0\.ddr4_dq[63]}]
set_property PACKAGE_PIN A25 [get_ports {DDR4_IF0\.ddr4_dq[59]}]
set_property PACKAGE_PIN B26 [get_ports {DDR4_IF0\.ddr4_dq[57]}]
set_property PACKAGE_PIN B27 [get_ports {DDR4_IF0\.ddr4_dq[58]}]
set_property PACKAGE_PIN D25 [get_ports {DDR4_IF0\.ddr4_dqs_t[7]}]
set_property PACKAGE_PIN D26 [get_ports {DDR4_IF0\.ddr4_dqs_c[7]}]
set_property PACKAGE_PIN C26 [get_ports {DDR4_IF0\.ddr4_dq[61]}]
set_property PACKAGE_PIN C27 [get_ports {DDR4_IF0\.ddr4_dq[56]}]
set_property PACKAGE_PIN E25 [get_ports {DDR4_IF0\.ddr4_dq[60]}]
set_property PACKAGE_PIN E26 [get_ports {DDR4_IF0\.ddr4_dq[62]}]
set_property PACKAGE_PIN D28 [get_ports {DDR4_IF0\.ddr4_dm_dbi_n[7]}]
set_property PACKAGE_PIN G26 [get_ports {DDR4_IF0\.ddr4_dq[50]}]
set_property PACKAGE_PIN G27 [get_ports {DDR4_IF0\.ddr4_dq[54]}]
set_property PACKAGE_PIN F28 [get_ports {DDR4_IF0\.ddr4_dq[53]}]
set_property PACKAGE_PIN E28 [get_ports {DDR4_IF0\.ddr4_dq[51]}]
set_property PACKAGE_PIN G25 [get_ports {DDR4_IF0\.ddr4_dqs_t[6]}]
set_property PACKAGE_PIN F25 [get_ports {DDR4_IF0\.ddr4_dqs_c[6]}]
set_property PACKAGE_PIN F27 [get_ports {DDR4_IF0\.ddr4_dq[49]}]
set_property PACKAGE_PIN E27 [get_ports {DDR4_IF0\.ddr4_dq[55]}]
set_property PACKAGE_PIN J26 [get_ports {DDR4_IF0\.ddr4_dq[48]}]
set_property PACKAGE_PIN H26 [get_ports {DDR4_IF0\.ddr4_dq[52]}]
set_property PACKAGE_PIN H27 [get_ports {DDR4_IF0\.ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN K26 [get_ports {DDR4_IF0\.ddr4_dq[47]}]
set_property PACKAGE_PIN K27 [get_ports {DDR4_IF0\.ddr4_dq[45]}]
set_property PACKAGE_PIN K28 [get_ports {DDR4_IF0\.ddr4_dq[41]}]
set_property PACKAGE_PIN J28 [get_ports {DDR4_IF0\.ddr4_dq[43]}]
set_property PACKAGE_PIN L25 [get_ports {DDR4_IF0\.ddr4_dqs_t[5]}]
set_property PACKAGE_PIN K25 [get_ports {DDR4_IF0\.ddr4_dqs_c[5]}]
set_property PACKAGE_PIN M27 [get_ports {DDR4_IF0\.ddr4_dq[42]}]
set_property PACKAGE_PIN L27 [get_ports {DDR4_IF0\.ddr4_dq[46]}]
set_property PACKAGE_PIN N24 [get_ports {DDR4_IF0\.ddr4_dq[44]}]
set_property PACKAGE_PIN M24 [get_ports {DDR4_IF0\.ddr4_dq[40]}]
set_property PACKAGE_PIN M25 [get_ports {DDR4_IF0\.ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN P26 [get_ports {DDR4_IF0\.ddr4_dq[36]}]
set_property PACKAGE_PIN N26 [get_ports {DDR4_IF0\.ddr4_dq[39]}]
set_property PACKAGE_PIN T28 [get_ports {DDR4_IF0\.ddr4_dq[33]}]
set_property PACKAGE_PIN R28 [get_ports {DDR4_IF0\.ddr4_dq[37]}]
set_property PACKAGE_PIN P24 [get_ports {DDR4_IF0\.ddr4_dqs_t[4]}]
set_property PACKAGE_PIN P25 [get_ports {DDR4_IF0\.ddr4_dqs_c[4]}]
set_property PACKAGE_PIN R26 [get_ports {DDR4_IF0\.ddr4_dq[32]}]
set_property PACKAGE_PIN R27 [get_ports {DDR4_IF0\.ddr4_dq[35]}]
set_property PACKAGE_PIN T25 [get_ports {DDR4_IF0\.ddr4_dq[34]}]
set_property PACKAGE_PIN R25 [get_ports {DDR4_IF0\.ddr4_dq[38]}]
set_property PACKAGE_PIN P28 [get_ports {DDR4_IF0\.ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN B34 [get_ports {DDR4_IF0\.ddr4_dq[25]}]
set_property PACKAGE_PIN A34 [get_ports {DDR4_IF0\.ddr4_dq[29]}]
set_property PACKAGE_PIN D34 [get_ports {DDR4_IF0\.ddr4_dq[26]}]
set_property PACKAGE_PIN C34 [get_ports {DDR4_IF0\.ddr4_dq[30]}]
set_property PACKAGE_PIN B35 [get_ports {DDR4_IF0\.ddr4_dqs_t[3]}]
set_property PACKAGE_PIN A35 [get_ports {DDR4_IF0\.ddr4_dqs_c[3]}]
set_property PACKAGE_PIN E35 [get_ports {DDR4_IF0\.ddr4_dq[24]}]
set_property PACKAGE_PIN D35 [get_ports {DDR4_IF0\.ddr4_dq[28]}]
set_property PACKAGE_PIN C36 [get_ports {DDR4_IF0\.ddr4_dq[31]}]
set_property PACKAGE_PIN B36 [get_ports {DDR4_IF0\.ddr4_dq[27]}]
set_property PACKAGE_PIN E36 [get_ports {DDR4_IF0\.ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN C37 [get_ports {DDR4_IF0\.ddr4_dq[19]}]
set_property PACKAGE_PIN B37 [get_ports {DDR4_IF0\.ddr4_dq[21]}]
set_property PACKAGE_PIN A37 [get_ports {DDR4_IF0\.ddr4_dq[17]}]
set_property PACKAGE_PIN A38 [get_ports {DDR4_IF0\.ddr4_dq[22]}]
set_property PACKAGE_PIN C38 [get_ports {DDR4_IF0\.ddr4_dqs_t[2]}]
set_property PACKAGE_PIN B39 [get_ports {DDR4_IF0\.ddr4_dqs_c[2]}]
set_property PACKAGE_PIN D39 [get_ports {DDR4_IF0\.ddr4_dq[20]}]
set_property PACKAGE_PIN C39 [get_ports {DDR4_IF0\.ddr4_dq[18]}]
set_property PACKAGE_PIN E37 [get_ports {DDR4_IF0\.ddr4_dq[23]}]
set_property PACKAGE_PIN D38 [get_ports {DDR4_IF0\.ddr4_dq[16]}]
set_property PACKAGE_PIN F38 [get_ports {DDR4_IF0\.ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN G37 [get_ports {DDR4_IF0\.ddr4_dq[11]}]
set_property PACKAGE_PIN F37 [get_ports {DDR4_IF0\.ddr4_dq[15]}]
set_property PACKAGE_PIN H36 [get_ports {DDR4_IF0\.ddr4_dq[10]}]
set_property PACKAGE_PIN G36 [get_ports {DDR4_IF0\.ddr4_dq[14]}]
set_property PACKAGE_PIN H37 [get_ports {DDR4_IF0\.ddr4_dqs_t[1]}]
set_property PACKAGE_PIN H38 [get_ports {DDR4_IF0\.ddr4_dqs_c[1]}]
set_property PACKAGE_PIN H34 [get_ports {DDR4_IF0\.ddr4_dq[8]}]
set_property PACKAGE_PIN G34 [get_ports {DDR4_IF0\.ddr4_dq[12]}]
set_property PACKAGE_PIN H39 [get_ports {DDR4_IF0\.ddr4_dq[9]}]
set_property PACKAGE_PIN G39 [get_ports {DDR4_IF0\.ddr4_dq[13]}]
set_property PACKAGE_PIN G35 [get_ports {DDR4_IF0\.ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN L37 [get_ports {DDR4_IF0\.ddr4_dq[2]}]
set_property PACKAGE_PIN K37 [get_ports {DDR4_IF0\.ddr4_dq[0]}]
set_property PACKAGE_PIN J34 [get_ports {DDR4_IF0\.ddr4_dq[7]}]
set_property PACKAGE_PIN J35 [get_ports {DDR4_IF0\.ddr4_dq[3]}]
set_property PACKAGE_PIN L38 [get_ports {DDR4_IF0\.ddr4_dqs_t[0]}]
set_property PACKAGE_PIN K38 [get_ports {DDR4_IF0\.ddr4_dqs_c[0]}]
set_property PACKAGE_PIN L35 [get_ports {DDR4_IF0\.ddr4_dq[6]}]
set_property PACKAGE_PIN K35 [get_ports {DDR4_IF0\.ddr4_dq[4]}]
set_property PACKAGE_PIN J38 [get_ports {DDR4_IF0\.ddr4_dq[1]}]
set_property PACKAGE_PIN J39 [get_ports {DDR4_IF0\.ddr4_dq[5]}]
set_property PACKAGE_PIN K36 [get_ports {DDR4_IF0\.ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN C31 [get_ports {DDR4_IF0\.ddr4_adr[13]}]
set_property PACKAGE_PIN B31 [get_ports {DDR4_IF0\.ddr4_adr[12]}]
set_property PACKAGE_PIN B29 [get_ports {DDR4_IF0\.ddr4_adr[2]}]
set_property PACKAGE_PIN A28 [get_ports {DDR4_IF0\.ddr4_adr[11]}]
set_property PACKAGE_PIN B32 [get_ports {DDR4_IF0\.ddr4_adr[3]}]
set_property PACKAGE_PIN A32 [get_ports {DDR4_IF0\.ddr4_adr[4]}]
set_property PACKAGE_PIN D29 [get_ports {DDR4_IF0\.ddr4_adr[7]}]
set_property PACKAGE_PIN C29 [get_ports {DDR4_IF0\.ddr4_adr[9]}]
set_property PACKAGE_PIN C32 [get_ports {DDR4_IF0\.ddr4_odt[0]}]
set_property PACKAGE_PIN C33 [get_ports {DDR4_IF0\.ddr4_adr[10]}]
set_property PACKAGE_PIN B30 [get_ports {DDR4_IF0\.ddr4_cs_n[0]}]
set_property PACKAGE_PIN A30 [get_ports {DDR4_IF0\.ddr4_adr[0]}]
set_property PACKAGE_PIN D30 [get_ports {DDR4_IF0\.ddr4_adr[5]}]
set_property PACKAGE_PIN G29 [get_ports {DDR4_IF0\.ddr4_adr[6]}]
set_property PACKAGE_PIN F29 [get_ports {DDR4_IF0\.ddr4_adr[16]}]
set_property PACKAGE_PIN E31 [get_ports {DDR4_IF0\.ddr4_ba[1]}]
set_property PACKAGE_PIN D31 [get_ports {DDR4_IF0\.ddr4_adr[14]}]
set_property PACKAGE_PIN G30 [get_ports {DDR4_IF0\.ddr4_adr[1]}]
set_property PACKAGE_PIN F30 [get_ports {DDR4_IF0\.ddr4_adr[15]}]
set_property PACKAGE_PIN F32 [get_ports {DDR4_IF0\.ddr4_reset_n}]
set_property PACKAGE_PIN E32 [get_ports {DDR4_IF0\.ddr4_bg[0]}]
set_property PACKAGE_PIN D33 [get_ports {DDR4_IF0\.ddr4_cke[0]}]
set_property PACKAGE_PIN F33 [get_ports {DDR4_IF0\.ddr4_ba[0]}]
set_property PACKAGE_PIN E33 [get_ports {DDR4_IF0\.ddr4_act_n}]
set_property PACKAGE_PIN H32 [get_ports {DDR4_IF0\.ddr4_adr[8]}]
set_property PACKAGE_PIN J29 [get_ports {DDR4_IF0\.ddr4_ck_t[0]}]
set_property PACKAGE_PIN H29 [get_ports {DDR4_IF0\.ddr4_ck_c[0]}]

set_property IOSTANDARD DIFF_SSTL12 [get_ports FPGA_DDR4_100M_CLK0P]
set_property IOSTANDARD DIFF_SSTL12 [get_ports FPGA_DDR4_100M_CLK0N]
set_property IOSTANDARD DIFF_SSTL12 [get_ports FPGA_DDR4_100M_CLK1P]
set_property IOSTANDARD DIFF_SSTL12 [get_ports FPGA_DDR4_100M_CLK1N]

####################################################################################
# Constraints from file : 'DAC_FPGA_pins.xdc'
####################################################################################

